### PR TITLE
Updates sample cert and admin keystore

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Description
Downstream change coming from security plugin: https://github.com/opensearch-project/security/pull/4061

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DarshitChanpura** [comment]
should be merged post https://github.com/opensearch-project/security/pull/4061 is merged

**Review by mch2 — APPROVED** [review]

**Comment by gaiksaya** [comment]
Hello reviewers,

This could be potential reason for failing tests with security atleast at the distribution level for 2.13.0.
Please review and merge. 

Thanks!

**Review by Rishikesh1159 — APPROVED** [review]

**Comment by mch2** [comment]
multi-node test workflow is currently broken on main unrelated to this.  Attempting to resolve that first

**Comment by mch2** [comment]
Haven't been able to resolve the bwc issue quickly.  Will go ahead with this to unblock testing of 2.13

**Pull request merged**
