### PR TITLE
Adding support for jdk 17

### PR DESCRIPTION
**Pull request by bharath-techie**
### Description
Adding support for JDK 17
 
### Issues Resolved
[List any issues this PR will resolve]
https://github.com/opensearch-project/asynchronous-search/issues/101
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@bharath-techie for JDK 17 we need to move to Gradle 7 (it is not supported by Gradle 6), I could help with that, wdyt?

**Comment by bharath-techie** [comment]
> @bharath-techie for JDK 17 we need to move to Gradle 7 (it is not supported by Gradle 6), I could help with that, wdyt?



> @bharath-techie for JDK 17 we need to move to Gradle 7 (it is not supported by Gradle 6), I could help with that, wdyt?

@reta Hi thanks for reaching out but gradle 7 support is being worked upon as part of this PR - https://github.com/opensearch-project/asynchronous-search/pull/110/files

**Comment by bharath-techie** [comment]
> @bharath-techie for JDK 17 we need to move to Gradle 7 (it is not supported by Gradle 6), I could help with that, wdyt?



> @bharath-techie for JDK 17 we need to move to Gradle 7 (it is not supported by Gradle 6), I could help with that, wdyt?

@reta Hi thanks for reaching out but gradle 7 support is being worked upon as part of this PR - https://github.com/opensearch-project/asynchronous-search/pull/110/files

**Comment by eirsep** [comment]
> @bharath-techie for JDK 17 we need to move to Gradle 7 (it is not supported by Gradle 6), I could help with that, wdyt?

Hi @reta 
I have raised a PR which is also upgrading the project to gradle 7
https://github.com/opensearch-project/asynchronous-search/runs/5560592397?check_suite_focus=true

**Comment by eirsep** [comment]
Lets split this PR into 2 different PRs -  one to remove jdk 8, which can be merged right away, and another to support jdk 17 which can follow #110

**Review by dblock — APPROVED** [review]

**Review by eirsep — APPROVED** [review]

**Pull request merged**
