### PR TITLE
Fix main build

### PR DESCRIPTION
**Pull request by Arpit-Bandejiya**
### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by bharath-techie — DISMISSED** [review]

**Comment by Arpit-Bandejiya** [comment]
```
/local/home/abandeji/workplace/asynchronous-search/src/main/java/org/opensearch/search/asynchronous/management/AsynchronousSearchManagementService.java:27: error: cannot find symbol
import org.opensearch.common.collect.ImmutableOpenMap;
                                    ^
  symbol:   class ImmutableOpenMap
  location: package org.opensearch.common.collect
/local/home/abandeji/workplace/asynchronous-search/src/main/java/org/opensearch/search/asynchronous/context/persistence/AsynchronousSearchPersistenceModel.java:51: error: cannot find symbol
            Version.writeVersion(Version.CURRENT, out);
                   ^
  symbol:   method writeVersion(Version,BytesStreamOutput)
  location: class Version
/local/home/abandeji/workplace/asynchronous-search/src/main/java/org/opensearch/search/asynchronous/context/persistence/AsynchronousSearchPersistenceModel.java:71: error: cannot find symbol
            Version.writeVersion(Version.CURRENT, out);
                   ^
  symbol:   method writeVersion(Version,BytesStreamOutput)
  location: class Version
/local/home/abandeji/workplace/asynchronous-search/src/main/java/org/opensearch/search/asynchronous/context/persistence/AsynchronousSearchPersistenceContext.java:85: error: cannot find symbol
                wrapperStreamInput.setVersion(Version.readVersion(wrapperStreamInput));
                                                     ^
  symbol:   method readVersion(NamedWriteableAwareStreamInput)
  location: class Version
/local/home/abandeji/workplace/asynchronous-search/src/main/java/org/opensearch/search/asynchronous/context/persistence/AsynchronousSearchPersistenceContext.java:105: error: cannot find symbol
            wrapperStreamInput.setVersion(Version.readVersion(wrapperStreamInput));
                                                 ^
  symbol:   method readVersion(NamedWriteableAwareStreamInput)
  location: class Version
/local/home/abandeji/workplace/asynchronous-search/src/main/java/org/opensearch/search/asynchronous/management/AsynchronousSearchManagementService.java:199: error: cannot find symbol
            ImmutableOpenMap<String, DiscoveryNode> dataNodes = clusterService.state().nodes().getDataNodes();
            ^
  symbol:   class ImmutableOpenMap
  location: class AsynchronousSearchManagementService
Note: /local/home/abandeji/workplace/asynchronous-search/src/main/java/org/opensearch/search/asynchronous/response/AsynchronousSearchResponse.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by Arpit-Bandejiya** [comment]
https://github.com/opensearch-project/OpenSearch/pull/7165/files
Seems like this refactoring is the issue.

**Comment by Arpit-Bandejiya** [comment]
```
> Task :compileTestJava FAILED
/local/home/abandeji/workplace/asynchronous-search/src/test/java/org/opensearch/search/asynchronous/management/AsynchronousSearchManagementServiceTests.java:200: error: incompatible types: IndexMetadata cannot be converted to ObjectCursor<IndexMetadata>
        for (ObjectCursor<IndexMetadata> cursor : metadata.indices().values()) {
                                                                           ^
/local/home/abandeji/workplace/asynchronous-search/src/test/java/org/opensearch/search/asynchronous/integTests/AsynchronousSearchStatsIT.java:70: error: cannot find symbol
        clusterService().state().nodes().getDataNodes().iterator().forEachRemaining(node -> {
                                                       ^
  symbol:   method iterator()
  location: interface Map<String,DiscoveryNode>
/local/home/abandeji/workplace/asynchronous-search/src/test/java/org/opensearch/search/asynchronous/integTests/AsynchronousSearchStatsIT.java:121: error: cannot find symbol
            clusterService().state().nodes().getDataNodes().iterator().forEachRemaining(node -> {
                                                           ^
  symbol:   method iterator()
  location: interface Map<String,DiscoveryNode>
/local/home/abandeji/workplace/asynchronous-search/src/test/java/org/opensearch/search/asynchronous/integTests/AsynchronousSearchStatsIT.java:246: error: cannot find symbol
        clusterService().state().nodes().getDataNodes().iterator().forEachRemaining(node -> {
                                                       ^
  symbol:   method iterator()
  location: interface Map<String,DiscoveryNode>
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /local/home/abandeji/workplace/asynchronous-search/src/test/java/org/opensearch/search/asynchronous/bwc/AsyncSearchBackwardsCompatibilityIT.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors
```

**Comment by Arpit-Bandejiya** [comment]
One error left:
```
(23-05-02 11:17:18) <0> [~/workplace/asynchronous-search]
dev-dsk-abandeji-2a-a1f0f3bd % ./gradlew build
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.6.1
  OS Info               : Linux 5.4.235-151.344.amzn2int.x86_64 (amd64)
  JDK Version           : 11 (Amazon Corretto JDK)
  JAVA_HOME             : /local/home/abandeji/.sdkman/candidates/java/11.0.16-amzn
  Random Testing Seed   : 780D5A14C037CDE0
  In FIPS 140 mode      : false
=======================================

> Task :compileTestJava FAILED
/local/home/abandeji/workplace/asynchronous-search/src/test/java/org/opensearch/search/asynchronous/management/AsynchronousSearchManagementServiceTests.java:200: error: incompatible types: IndexMetadata cannot be converted to ObjectCursor<IndexMetadata>
        for (ObjectCursor<IndexMetadata> cursor : metadata.indices().values()) {
                                                                           ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /local/home/abandeji/workplace/asynchronous-search/src/test/java/org/opensearch/search/asynchronous/bwc/AsyncSearchBackwardsCompatibilityIT.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

**Review by bharath-techie — APPROVED** [review]

**Comment by Arpit-Bandejiya** [comment]
@gaiksaya  please run the workflows to update the 2.8 builds

**Review by bharath-techie — APPROVED** [review]

**Review by dhruv16dhr — APPROVED** [review]

**Pull request merged**
