### PR TITLE
Make sure qualifier is default to alpha1

### LINKED ISSUE #103: Add support for build version qualifiers.
Coming from https://github.com/opensearch-project/opensearch-build/issues/1632, add support for `-Dbuild.version_qualifier=`. 

The distribution build process now supports passing additional optional qualifiers other than the 3 digit versions, e.g. `2.0.0-alpha1`. Add the ability to pass additional qualifier to build scripts, and generate artifacts with a version that includes the qualifier.

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Make sure qualifier is default to alpha1
 
### Issues Resolved
#103
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by CEHENKLE — DISMISSED** [review]

**Review by bbarani — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
The errors are expected as we currently do not have security and PA ready for docker to run.

**Comment by peterzhuamazon** [comment]
The image pulling of docker is success here.

**Review by CEHENKLE — APPROVED** [review]

**Review by bbarani — APPROVED** [review]

**Comment by eirsep** [comment]
Why was this merged before the CI is fixed? Our current PRs are failing CI. 

@bbarani @peterzhuamazon @CEHENKLE 


cc: @dhruv16dhr @bharath-techie @Bukhtawar

**Comment by dhruv16dhr** [comment]
@CEHENKLE @dblock @peterzhuamazon 

AsyncSearch plugin team is working on 2.0.0 open issues and have related PRs which are blocked as CI is failing due to [this PR](https://github.com/opensearch-project/asynchronous-search/pull/123)

Can this be reverted and merged back once docker image is available?

**Pull request merged**
