### PR TITLE
Staging for version increment automation

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
This is the staging PR for to execute workflows that auto raise the version increment PR's
Example: https://github.com/prudhvigodithi/asynchronous-search/pull/1

### Issues Resolved
Part of: https://github.com/opensearch-project/opensearch-build/issues/1375
From solution: https://github.com/opensearch-project/opensearch-build/issues/1375#issuecomment-1159476686
Related issue: https://github.com/opensearch-project/asynchronous-search/issues/154

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Referenced old 1.x version increment PR https://github.com/opensearch-project/asynchronous-search/pull/155.

**Comment by bharath-techie** [comment]
@prudhvigodithi can you fix build failures, or is this related to gradle check failures which needs a fix.

**Comment by prudhvigodithi** [comment]
> @prudhvigodithi can you fix build failures, or is this related to gradle check failures which needs a fix.

Hey @bharath-techie I assume these failure are not caused with this change, can you also please confirm?
Thank you

**Comment by prudhvigodithi** [comment]
Hey @bharath-techie can you please take a look at those failures and confirm the cause, I'm sure its not because of this change :) 
Thank you

**Comment by bharath-techie** [comment]
```
Execution failed for task ':compileTestJava'.
> Could not resolve all dependencies for configuration ':testCompileClasspath'.
   > Conflict(s) found for the following module(s):
       - junit:junit between versions 4.13.2 and 4.12
     Run with:
         --scan or
         :dependencyInsight --configuration testCompileClasspath --dependency junit:junit
     to get more insight on how to solve the conflict.
```
This is the error we are getting.

**Comment by prudhvigodithi** [comment]
Hey @bharath-techie I'm sure this is not with this PR, was this always failing for 1.x?
Thank you 
@bbarani

**Comment by bharath-techie** [comment]
https://github.com/opensearch-project/asynchronous-search/pull/167/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R84

@prudhvigodithi Can you add this line and re raise PR ?

**Comment by prudhvigodithi** [comment]
Hey @bharath-techie I have updated the PR with change in Junit version.
Thank you

**Review by bharath-techie — APPROVED** [review]

**Review by dhruv16dhr — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Hey @dhruv16dhr @bharath-techie I dont see this is backported to 1.3 branch, can you please take a look?
Thank you

**Pull request merged**
