### PR TITLE
 Increment version to 2.8

### PR DESCRIPTION
**Pull request by Arpit-Bandejiya**
### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Arpit-Bandejiya** [comment]
```
* What went wrong:
Could not determine the dependencies of task ':thirdPartyAudit'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find org.opensearch:common-utils:2.8.0.0-SNAPSHOT.
     Searched in the following locations:
       - file:/home/abandeji/.m2/repository/org/opensearch/common-utils/2.8.0.0-SNAPSHOT/maven-metadata.xml
       - file:/home/abandeji/.m2/repository/org/opensearch/common-utils/2.8.0.0-SNAPSHOT/common-utils-2.8.0.0-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/org/opensearch/common-utils/2.8.0.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/opensearch/common-utils/2.8.0.0-SNAPSHOT/common-utils-2.8.0.0-SNAPSHOT.pom
       - https://plugins.gradle.org/m2/org/opensearch/common-utils/2.8.0.0-SNAPSHOT/maven-metadata.xml
       - https://plugins.gradle.org/m2/org/opensearch/common-utils/2.8.0.0-SNAPSHOT/common-utils-2.8.0.0-SNAPSHOT.pom
       - https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/common-utils/2.8.0.0-SNAPSHOT/maven-metadata.xml
       - https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/common-utils/2.8.0.0-SNAPSHOT/common-utils-2.8.0.0-SNAPSHOT.pom
     Required by:
         project :
```

**Comment by Arpit-Bandejiya** [comment]
The repo doesn't have common-utils 2.8 build. Will wait for this PR merge: https://github.com/opensearch-project/common-utils/issues/417

**Comment by Arpit-Bandejiya** [comment]
The local build of the common-util project is succeeding. Also seems like the latest build had a successful run https://build.ci.opensearch.org/job/distribution-build-opensearch/7788/

@gaiksaya  any help here? What could be causing the common-util to not being present in maven repo?

**Comment by Arpit-Bandejiya** [comment]
Also aftre caching the 2.8 build of common-utils the build is succeeding:

**Comment by gaiksaya** [comment]
> The local build of the common-util project is succeeding. Also seems like the latest build had a successful run https://build.ci.opensearch.org/job/distribution-build-opensearch/7788/
> 
> @gaiksaya any help here? What could be causing the common-util to not being present in maven repo?

I see it now after manually triggering the maven publish workflow: https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/common-utils/2.8.0.0-SNAPSHOT/
The maven publishing job has been moved to each repository respectively. 
Tagging the maintainers of common-utils: @getsaurabh02 @lezzago @bowenlan-amzn

**Review by bharath-techie — APPROVED** [review]

**Review by dhruv16dhr — APPROVED** [review]

**Pull request merged**
